apple = Product.create(name:"apple")
pear = Product.create(name:"pear")
onion = Product.create(name:"onion")
carrot = Product.create(name:"carrot")
grape = Product.create(name:"grape")
strawberry = Product.create(name:"strawberry")
celery = Product.create(name:"celery")
tomato = Product.create(name:"tomato")
potato = Product.create(name:"potato")
egg = Product.create(name:"egg")

v1 = Vendor.create(name:"Happy Vendors")
v2 = Vendor.create(name:"Middle Management")
v3 = Vendor.create(name:"Darth's Corner Store")
v4 = Vendor.create(name:"Luke's")

entry1 = PurchaseOrder.create(product_id: carrot.id, vendor_id: v1.id, quantity: 25, unit_price: 2.00, sku: 123456789, order_date: Date.new(2020, 12, 2), processed: false, total_unit_price: 50)
entry2 = PurchaseOrder.create(product_id: pear.id, vendor_id: v1.id, quantity: 20, unit_price: 4.00, sku: 234567891, order_date: Date.new(2020, 2, 10), processed: false, total_unit_price: 80)
entry3 = PurchaseOrder.create(product_id: egg.id, vendor_id: v2.id, quantity: 50, unit_price: 1.50, sku: 345678912, order_date: Date.new(2020, 12, 2), processed: true, total_unit_price: 75)
entry4 = PurchaseOrder.create(product_id: onion.id, vendor_id: v2.id, quantity: 50, unit_price: 0.89, sku: 456789123, order_date: Date.new(2020, 12, 2), processed: false, total_unit_price: 44.50)
entry5 = PurchaseOrder.create(product_id: egg.id, vendor_id: v3.id, quantity: 50, unit_price: 0.50, sku: 567891234, order_date: Date.new(2020, 12, 2), processed: true, total_unit_price: 25)

